### ISSUE TITLE
AspNet.Security.OAuth.Weibo 3.0 not work!

### ISSUE THREAD

**Issue by vicenteyu** [aspnet-contrib/AspNet.Security.OAuth.Providers#355]
when Scope=[], 
result: AspNet.Security.OAuth.Weibo.WeiboAuthenticationHandler|Error from RemoteAuthentication: OAuth token endpoint failure: Status: BadRequest;

when Scope=["email"]
result: An error occurred while retrieving the email address associated to the user profile.

**Comment by martincostello** [comment]
If you could provide some more exception details for the case with the email scope set, we could look at providing a fix of it’s a bug and not a configuration issue or some transient service error on Weibo’s side.

This package was community contributed and I don’t personally have a Weibo account to test it with.

**Comment by vicenteyu** [comment]
2019-11-08 02:13:01.5426|12|INFO|AspNet.Security.OAuth.Weibo.WeiboAuthenticationHandler|AuthenticationScheme: Weibo was challenged. 
2019-11-08 02:13:01.9125|0|WARN|AspNet.Security.OAuth.Weibo.WeiboAuthenticationHandler|An error occurred while retrieving the email address associated with the logged in user: the remote server returned a Forbidden response with the following payload: Server: nginx/1.6.1
Date: Thu, 07 Nov 2019 18:12:59 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
 {"error":"access_denied","error_code":21330,"request":"/2/account/profile/email.json"}. 
2019-11-08 02:13:01.9207|4|INFO|AspNet.Security.OAuth.Weibo.WeiboAuthenticationHandler|Error from RemoteAuthentication: An error occurred while retrieving the email address associated to the user profile.. 
2019-11-08 02:13:01.9207|1|ERROR|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request. System.Exception: An error was encountered while handling the remote login.
 ---> System.Net.Http.HttpRequestException: An error occurred while retrieving the email address associated to the user profile.
   at AspNet.Security.OAuth.Weibo.WeiboAuthenticationHandler.GetEmailAsync(OAuthTokenResponse tokens) in /_/src/AspNet.Security.OAuth.Weibo/WeiboAuthenticationHandler.cs:line 103
   at AspNet.Security.OAuth.Weibo.WeiboAuthenticationHandler.CreateTicketAsync(ClaimsIdentity identity, AuthenticationProperties properties, OAuthTokenResponse tokens) in /_/src/AspNet.Security.OAuth.Weibo/WeiboAuthenticationHandler.cs:line 66
   at Microsoft.AspNetCore.Authentication.OAuth.OAuthHandler`1.HandleRemoteAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   --- End of inner exception stack trace ---

**Comment by martincostello** [comment]
The description of that error code is: _“ 21330: User or authorization server denies access to data”_

https://topic.alibabacloud.com/a/sina-weibo-error-code-detailed_8_8_31193543.html

**Comment by vicenteyu** [comment]
set scope=[] to skip get email.
then:
2019-11-08 04:54:08.6440|4|INFO|AspNet.Security.OAuth.Weibo.WeiboAuthenticationHandler|Error from RemoteAuthentication: OAuth token endpoint failure: Status: BadRequest;Headers: Server: nginx/1.6.1
Date: Thu, 07 Nov 2019 20:54:06 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Pragma: No-cache
Cache-Control: no-cache
;Body: {"error":"invalid_grant","error_code":21325,"request":"/oauth2/access_token","error_uri":"/oauth2/access_token","error_description":"invalid authorization code:8d5c2d4f2c7381fac2be44c0ca234357"};. 
2019-11-08 04:54:08.7285|1|ERROR|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|An unhandled exception has occurred while executing the request. System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: OAuth token endpoint failure: Status: BadRequest;Headers: Server: nginx/1.6.1
Date: Thu, 07 Nov 2019 20:54:06 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Pragma: No-cache
Cache-Control: no-cache
;Body: {"error":"invalid_grant","error_code":21325,"request":"/oauth2/access_token","error_uri":"/oauth2/access_token","error_description":"invalid authorization code:8d5c2d4f2c7381fac2be44c0ca234357"};
   --- End of inner exception stack trace ---

**Comment by martincostello** [comment]
Looking at this page with Google Translate, there’s a list of scopes available: https://open.weibo.com/wiki/Scope

You could try `all`, but with the documentation all being in Chinese and me not having an account there’s not much more I can help with, you could try reaching out to the user in the commit history who originally created the Weibo provider.

**Comment by vicenteyu** [comment]
scope=["all"]  same as scope=[] 
Thank you.

**Comment by kinosang** [comment]
You cannot use `email` and some other scopes except Weibo assign the permissions to your app, but they closed the entry for applying that.

An `invalid authorization code` error may be caused by code reusing, do not refresh the callback page.

Just do `options.Scope.Remove("email");` and start from the beginning of the OAuth login may solve your problem.

**Comment by vicenteyu** [comment]
Solved! Thanks!
