### ISSUE TITLE
Yahoo Social Directory (User Profile) API changing

### ISSUE THREAD

**Issue by benjaminsampica** [aspnet-contrib/AspNet.Security.OAuth.Providers#392]
**Describe the bug**
This is a new bug with the Yahoo login authentication handler, having started yesterday (for us at least). Our application uses Yahoo to authenticate users and the ```OAuth.Yahoo``` library is doing the heavy lifting retrieving the profile information, tokens, etc. As of yesterday afternoon, we now receive an error.

**Steps To reproduce**
Try and authenticate with the Yahoo authentication handler in `AspNet.Security.OAuth.Yahoo.YahooAuthenticationHandler`

**Expected behaviour**
User is authenticated and profile information is returned and parsed by the Yahoo authentication handler.

**Actual behaviour**
After signing in with valid credentials on Yahoo's external provider page, the user is redirected back to the ```/sigin-yahoo``` endpoint and receives the following stacktrace:

```
System.Exception: An error was encountered while handling the remote login.

 ---> System.Net.Http.HttpRequestException: An error occurred while retrieving the user profile.

   at AspNet.Security.OAuth.Yahoo.YahooAuthenticationHandler.CreateTicketAsync(ClaimsIdentity identity, AuthenticationProperties properties, OAuthTokenResponse tokens) in /_/src/AspNet.Security.OAuth.Yahoo/YahooAuthenticationHandler.cs:line 56

   at Microsoft.AspNetCore.Authentication.OAuth.OAuthHandler`1.HandleRemoteAuthenticateAsync()

   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()

   --- End of inner exception stack trace ---

   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**System information:**
 - OS: Windows 10
 - Library Version: 3.0.0
 - .NET version: ASP.NET Core 3.1

**Additional context**

We believe it is linked to the warning banner that now resides on their OAuth page https://developer.yahoo.com/oauth2/guide/
and leads to here: 
https://developer.yahoo.com/oauth/social-directory-eol/

**Comment by martincostello** [comment]
This change is now available from NuGet.org: https://www.nuget.org/packages/AspNet.Security.OAuth.Yahoo/3.1.0
