### ISSUE TITLE
Linkedin error: 'You need to pass the scope parameter' 

### ISSUE THREAD

**Issue by vincent-scw** [aspnet-contrib/AspNet.Security.OAuth.Providers#402]
**Describe the bug**
I am using Linkedin as provider, but get error as "You need to pass the 'scope' parameter"

**Steps To reproduce**
Added the middlewear as the same as in sample.
```
services.AddAuthentication()
                .AddLinkedIn(options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;

                    options.ClientId = Configuration["LinkedIn:ClientId"];
                    options.ClientSecret = Configuration["LinkedIn:ClientSecret"];

                    options.CallbackPath = new PathString("/linkedin");
                    options.SaveTokens = true;
                    
                })
```
But get error as ```http://localhost:30000/linkedin?error=invalid_request&error_description=You+need+to+pass+the+%22scope%22+parameter&state=xxx```

**Expected behaviour**
It should redirect to Linkedin login page

**Actual behaviour**
Error

**System information:**
 - OS: [e.g. Windows 10]
 - Library Version [e.g. 2.0.1]
 - .NET version (e.g. output from `dotnet --info`)

**Additional context**
I've tried with **Github**. It works **as expected**.
```
 services.AddAuthentication()
                .AddGitHub(options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;

                    options.ClientId = Configuration["Github:ClientId"];
                    options.ClientSecret = Configuration["Github:ClientSecret"];

                    options.CallbackPath = new PathString("/github");
                    options.SaveTokens = true;

                })
```

**Comment by martincostello** [comment]
What version of the provider are you using?

**Comment by vincent-scw** [comment]
@martincostello v2

**Comment by martincostello** [comment]
Can you give me the _exact_ version of the NuGet package please?

**Comment by vincent-scw** [comment]
Sorry, it is the latest, 3.0.0.0

**Comment by martincostello** [comment]
Hmm, if it’s 2.1.0 or later then I’m not sure why you would get this error.

The code does specify the scopes:

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/ff9785e2071d3e5a7337615d6a90d8b4f077c80e/src/AspNet.Security.OAuth.LinkedIn/LinkedInAuthenticationOptions.cs#L34-L35

Are you able to share some debug logs showing what the provider is doing under the hood?

**Comment by vincent-scw** [comment]
here is the log
```
Microsoft.AspNetCore.Mvc.ChallengeResult:Information: Executing ChallengeResult with authentication schemes (LinkedIn).
AspNet.Security.OAuth.LinkedIn.LinkedInAuthenticationHandler:Information: AuthenticationScheme: LinkedIn was challenged.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action JayCoder.MusicStore.Projects.IdentityServer.Quickstart.UI.ExternalController.Challenge (JayCoder.MusicStore.Projects.IdentityServer) in 2917.1474ms
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 2964.4805ms 302 
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:30000/linkedin?error=invalid_request&error_description=You+need+to+pass+the+%22scope%22+parameter&state=CfDJ8DpQYFjZrkBPpRB-yZzM_3WSByiOrrn-BNub0gtoq2Mkgr6sWd6ex2O2zwCX2BUDqFmG2UhTUYU0_zFiT2kYnFnmkR_Sg2Q91BftK_nSdgNj01VHW3242L_e73TNhMwXsXrHoGlD49K4qeAVeP3YdnLW6s_3JI0iXEyN_TmYpqaQfFOGSVfQQikwNdWmwswsWW8TZ66eZL3ZQ5tTohxpyImAZCvlJ5vIRd7grlck0FUfX1ONKRbZA-ekJRAWK5Phu6R7kv3ZPeHvHv9OAZX-ksQ  
AspNet.Security.OAuth.LinkedIn.LinkedInAuthenticationHandler:Information: Error from RemoteAuthentication: invalid_request;Description=You need to pass the "scope" parameter.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.17\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.17\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.17\System.IO.MemoryMappedFiles.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Server.Kestrel:Error: Connection id "0HLUSACV75FCP", Request id "0HLUSACV75FCP:00000003": An unhandled exception was thrown by the application.

System.Exception: An error was encountered while handling the remote login. ---> System.Exception: invalid_request;Description=You need to pass the "scope" parameter
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() in C:\local\identity\server4\IdentityServer4\src\Hosting\FederatedSignOut\AuthenticationRequestHandlerWrapper.cs:line 38
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by martincostello** [comment]
Are you able to include the debug logs showing the HTTP requests being made, rather than just the exception? It might provide some more context to see what requests are actually being made to LinkedIn.

It's possible that LinkedIn have changed their API and broken the integration: https://github.com/nvh95/react-linkedin-login-oauth2/issues/17#issuecomment-569258163

**Comment by martincostello** [comment]
Looking at our code, we don't customise the handling of scopes for LinkedIn, so it will use the base class' default behavior of sending space-delimited scopes in the request:

https://github.com/dotnet/aspnetcore/blob/16e25867248cb446bf1bba3f975c6e676b52ba6e/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L302

https://github.com/dotnet/aspnetcore/blob/16e25867248cb446bf1bba3f975c6e676b52ba6e/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L263-L272

https://github.com/dotnet/aspnetcore/blob/16e25867248cb446bf1bba3f975c6e676b52ba6e/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L293

Could this just be a configuration issue and a bad error message? https://github.com/sahat/satellizer/issues/1139#issuecomment-542730780

**Comment by vincent-scw** [comment]
My bad. I was doing the test in two projects. One references to version 2.0.0, another references to version 3.0.0
In 2.0.0, it has this issue (scopes 'r_liteprofile' & 'r_emailaddress' are missing ). But in 3.0.0, it works properly.
