### ISSUE TITLE
Discord: oath state was missing or invalid.

### ISSUE THREAD

**Issue by AraHaan** [aspnet-contrib/AspNet.Security.OAuth.Providers#436]
**Describe the bug**
_A clear and concise description of what the bug is. State which provider(s) the bug relates to._
I started randomly getting this on an endpoint of mine:
```cs
AspNet.Security.OAuth.Discord.DiscordAuthenticationHandler: Information: Error from RemoteAuthentication: The oauth state was missing or invalid..
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: The oauth state was missing or invalid.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Steps To reproduce**
_A concise and repeatable example of how to illustrate the issue._
I setup the package (latest stable on nuget) up (I think properly) and then started making requests to the ``/signin`` endpoint, which redirects to the discord oauth which then redirects to another endpoint (this one that then throws this exception)/

**Expected behaviour**
_A clear and concise description of what you expected to happen._
Everything to work just fine and properly.

**Actual behaviour**
_A clear and concise description of what actually happened. If an exception occurred, please include a stack trace if available._
The stack trace above.

**System information:**
 - OS: latest insider preview of Windows 10
 - Library Version: latest stable version from nuget.org.
 - .NET version:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.6.20272.11
 Commit:    c302b11ede

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20150
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.6.20272.11\

Host (useful for support):
  Version: 5.0.0-preview.6.20271.10
  Commit:  c44dc40b76

.NET SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview1-014459 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015151 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.6.20272.11 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview1.19508.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.6.20271.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20271.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview1.19506.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.6.20272.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Additional context**
_Add any other context about the problem here._

I have no idea what exactly caused this.

**Comment by martincostello** [comment]
> "latest stable version from nuget.org."

Things change over time - please state _exactly_ which version you are using as-per your `.csproj` file.

> The oath state was missing or invalid.

This is usually a configuration problem with the app with the callback URL and/or cookie settings causing the correlation information the OAuth 2.0 providers use to transfer state between the OAuth provider and your app using the cookies.

Here's two examples:
  * #431
  * [_The oauth state was missing or invalid. An error was encountered while handling the remote login_](https://stackoverflow.com/questions/57164127/the-oauth-state-was-missing-or-invalid-an-error-was-encountered-while-handling)

Please share some relevant application configuration code showing how you are setting your app up.

Is this a .NET 5 app? The information shows you are using a build of .NET Core 5 preview 6, but .NET 5 preview 6 hasn't shipped yet, so there's no guarantee the provider(s) will work with .NET 5 yet.

**Comment by AraHaan** [comment]
I am using the preview sdk yes but targeting netcoreapp3.1 for now on this project at least.

As to the package version it is version 3.1.1.

As to the setup I basically do this in my startup.cs

```cs
    public class Startup
    {
        public Startup(IConfiguration configuration)
            => this.Configuration = configuration;

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            this.Configuration["Discord:ClientId"] = "[the discord client id]";
            this.Configuration["Discord:ClientSecret"] = "[the discord client secret]";
            services.AddRouting();
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            })
            .AddCookie(options =>
            {
                options.LoginPath = "/signin";
                options.LogoutPath = "/signout";
            })
            .AddDiscord(options =>
            {
                options.ClientId = this.Configuration["Discord:ClientId"];
                options.ClientSecret = this.Configuration["Discord:ClientSecret"];
                options.CallbackPath = "/videos";
                options.Scope.Add("guilds");
                options.Scope.Add("guilds.join");
                options.Scope.Add("identify");
            });

            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public static void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
```

Then on a controller:
```cs
    [ApiController]
    public class VideosController : ControllerBase
    {
        [HttpGet("/signin")]
        public async Task<IActionResult> SignIn()
        {
            // Instruct the middleware corresponding to the requested external identity
            // provider to redirect the user agent to its own authorization endpoint.
            // Note: the authenticationScheme parameter must match the value configured in Startup.cs
            return this.Challenge(new AuthenticationProperties { RedirectUri = "/videos" }, "Discord");
        }

        [HttpGet("/signout")]
        [HttpPost("/signout")]
        public IActionResult SignOut()
        {
            // Instruct the cookies middleware to delete the local cookie created
            // when the user agent is redirected from the external identity provider
            // after a successful authentication flow (e.g Google or Facebook).
            return this.SignOut(new AuthenticationProperties { RedirectUri = "/videos" },
                CookieAuthenticationDefaults.AuthenticationScheme);
        }

        // other things in the controller that uses the [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)] attribute.
    }
```

**Comment by martincostello** [comment]
My guess would be that it’s something to do with the fact the callback URL has been changed to `"/videos"`. If you use the default callback, does it work?

Also from your sample I would highly recommend removing the GET from the sign-out handler, as that would allow malicious users to annoy users by sharing a link that logs them out of your app without any user interaction.

**Comment by AraHaan** [comment]
ah, I thought the callback url field was to tell it what the redirect url is (that I configured on the discord side of things on the bot application).

**Comment by martincostello** [comment]
No, it’s the URL for the OAuth provider to direct the user back to to complete authentication and the exchange of tokens. The original page they wanted to view is encoded within that data.

**Comment by AraHaan** [comment]
Ah I see

**Comment by AraHaan** [comment]
Well it seems like it works however now discord says the redirect url is invalid after that.

Also after the verifications my code also requires other things on it as well (like pulling the discord username (with the discriminator combined), user id, the servers they are in, a way to have it somehow add them to the discord server on their behalf, and finally their discord avatar url as well.

This is basically how I got another of my endpoints written on the api controller (currently)
```cs
[Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
        [HttpGet("/videos")]
        public async Task<IActionResult> GetVideos([FromQuery(Name = "code")] string code, [FromQuery(Name = "state")] string state)
        {
            if (!DiscordVerifierHelper.Services.GetRequiredService<DiscordAuthorizationsClient>().DiscordAccessTokens.HasState(state))
            {
                await DiscordVerifierHelper.Services.GetRequiredService<DiscordAuthorizationsClient>().ExchangeCode(code, state).ConfigureAwait(false);
            }

            var auth = DiscordVerifierHelper.Services.GetRequiredService<DiscordAuthorizationsClient>().DiscordAccessTokens.GetFromState(state);
            var content = File.ReadAllText("videos.html.in");
            content = content.Replace("img_avatar.png", auth!.AvatarURL, StringComparison.Ordinal).Replace("something#0000", auth.FullName, StringComparison.Ordinal);
            content = content.Replace("<!-- results -->", @"<br>
<div id=""demobox"">
Nothing found.
</div>", StringComparison.Ordinal);
            // TODO: Get Videos in some way depending on patron status by looking at the discord roles.
            // <br>
            // <div id="demobox">
            // <div id="videos-flex">
            // <text>&nbsp</text>
            // <img src="img_avatar.png" alt="video thumbnail" style="width:50px">
            // <text>&nbsp</text>
            // <a href="url">video name</a>
            // </div>
            // </div>
            return this.Content(content);
        }
```

**Comment by AraHaan** [comment]
@martincostello alright so got discord to say that it is valid (sometimes) yet it still randomly sometimes says the redirect url is invalid.

**Comment by martincostello** [comment]
If Discord now says your redirect URI is valid, then I'm not sure what you need help with. You're logged in and should have claims in the logged in user available and/or the Discord tokens if `SaveTokens` is set to `true`.

Otherwise, it seems you're asking us questions about how the Discord API works, which is outside of the scope of this library.

**Comment by AraHaan** [comment]
Well I figured out how to get the claims, I just did not know how to get the claims in the message above then found out how. However now it seems when I asked someone else to also test the signin endpoint that discord says for them that it is invalid after the first authentication is placed on the application.

I am basically wanting to allow multiple users and sadly it might be possible that a couple of users could login to it at the same time.

**Comment by AraHaan** [comment]
@martincostello After more tests after figuring out how to obtain the claims information it seems that sometimes at random the url the generated discord urls makes discord think the redirect urls are i valid.

And sadly I need a way to support multiple people as well on logging in and whatnot.

**Comment by AraHaan** [comment]
It seems now I get this every time anyone tries to sign in:

```
An unhandled exception occurred while processing the request.
Exception: Correlation failed.

Unknown location
Exception: An error was encountered while handling the remote login.

Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
```

**Comment by i542873057** [comment]
> It seems now I get this every time anyone tries to sign in:
> 
> ```
> An unhandled exception occurred while processing the request.
> Exception: Correlation failed.
> 
> Unknown location
> Exception: An error was encountered while handling the remote login.
> 
> Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
> ```

I have the same problem as you. Have you solved it
