### ISSUE TITLE
WindowsCryptographicException during authentication flow

### ISSUE THREAD

**Issue by paulers** [aspnet-contrib/AspNet.Security.OAuth.Providers#505]
After the Apple auth screen, upon returning to my app, I'm getting a WindowsCryptographicException.

Here is the relevant code:
```csharp
.AddApple("Apple", options =>
{
    options.GenerateClientSecret = true;
    options.ClientId = Configuration["Provider:Apple:ClientId"];
    options.KeyId = appleKeyId;
    options.TeamId = Configuration["Provider:Apple:TeamId"];
    options.PrivateKeyBytes = _ => Task.FromResult(appleP8KeyBytes);
    //options.UsePrivateKey((keyId) => Environment.ContentRootFileProvider.GetFileInfo($"AuthKey_{appleKeyId}.p8"));
});
```

I can verify all the values are loading correctly from Configuration and the `appleP8KeyBytes` var has the byte array converted from base64 string containing the key (minus trivia -- see another issue about taking in a string instead of a file). As a side note, the `UsePrivateKey` method did not work for me at all (running in Azure).

I couldn't test this locally since setting up IIS express with a self-signed cert is a nightmare, but I could find the stack in the logs:
```
EventId: 2
RequestId: 800035e8-0001-6600-b63f-84710c7967bb
RequestPath: /signin-apple
SpanId: |a84da57-4e424c470fb77272.
TraceId: a84da57-4e424c470fb77272
ParentId: 

Connection ID "7349874597774243050", Request ID "800035e8-0001-6600-b63f-84710c7967bb": An unhandled exception was thrown by the application.

Exception: 
System.Exception: An error was encountered while handling the remote login.
 ---&gt; Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified.
   at System.Security.Cryptography.CngKeyLite.ImportKeyBlob(String blobType, ReadOnlySpan`1 keyBlob, Boolean encrypted, ReadOnlySpan`1 password)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8(ReadOnlySpan`1 keyBlob)
   at System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32&amp; bytesRead)
   at System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportPkcs8PrivateKey(ReadOnlySpan`1 source, Int32&amp; bytesRead)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.CreateAlgorithm(Byte[] keyBlob)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateNewSecretAsync(AppleGenerateClientSecretContext context)
   at AspNet.Security.OAuth.Apple.Internal.DefaultAppleClientSecretGenerator.GenerateAsync(AppleGenerateClientSecretContext context)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationEvents.&lt;&gt;c.&lt;&lt;-ctor&gt;b__10_0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at AspNet.Security.OAuth.Apple.AppleAuthenticationEvents.GenerateClientSecret(AppleGenerateClientSecretContext context)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.ExchangeCodeAsync(OAuthCodeExchangeContext context)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.HandleRemoteAuthenticateAsync(Dictionary`2 parameters)
   at AspNet.Security.OAuth.Apple.AppleAuthenticationHandler.HandleRemoteAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Kymeta.Cloud.Commons.AspNet.ApiVersion.ApiVersionMiddleware.Invoke(HttpContext context)
   at Kymeta.Cloud.Services.Access.Startup.&lt;&gt;c.&lt;&lt;Configure&gt;b__8_1&gt;d.MoveNext() in C:\Repos\Sandbox\Kymeta.Cloud.Services.Access\Kymeta.Cloud.Services.Access\Startup.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
```

**System information:**
netcoreapp3.1
Azure App Service

**Comment by paulers** [comment]
Turns out adding WEBSITE_LOAD_USER_PROFILE=1 to Azure App Configuration fixed the issue. Now, failing to authenticate and the result has no information. :-(
