### ISSUE TITLE
AspNet.Security.OAuth.Nextcloud  InvalidOperationException: sub claim is missing

### ISSUE THREAD

**Issue by cyjbox** [aspnet-contrib/AspNet.Security.OAuth.Providers#521]
### Provider name

AspNet.Security.OAuth.Nextcloud

sorry, I don't know where to post this, if I bother you,you can close this,
I use AspNet.Security.OAuth.Nextcloud to authenticate user,the .net sdk version is 5, I setup the Nextcloud server myself,the code is:

services.AddAuthentication(options =>

{
options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
})
.AddNextcloud(options =>
{
options.ClientId = "";
options.ClientSecret = "";
options.AuthorizationEndpoint = "";
options.TokenEndpoint = "";
options.UserInformationEndpoint = "*";
});

everything is ok, but when nextcloud redirect to https://localhost:5001/signin-nextcloud，the Identityserver hav an exception : InvalidOperationException: sub claim is missing

next is the call stack:

InvalidOperationException: sub claim is missing
IdentityServer4.Hosting.IdentityServerAuthenticationService.AssertRequiredClaims(ClaimsPrincipal principal)
IdentityServer4.Hosting.IdentityServerAuthenticationService.AugmentPrincipal(ClaimsPrincipal principal)
IdentityServer4.Hosting.IdentityServerAuthenticationService.SignInAsync(HttpContext context, string scheme, ClaimsPrincipal principal, AuthenticationProperties properties)
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Show raw exception details

System.InvalidOperationException: sub claim is missing
   at IdentityServer4.Hosting.IdentityServerAuthenticationService.AssertRequiredClaims(ClaimsPrincipal principal)
   at IdentityServer4.Hosting.IdentityServerAuthenticationService.AugmentPrincipal(ClaimsPrincipal principal)
   at IdentityServer4.Hosting.IdentityServerAuthenticationService.SignInAsync(HttpContext context, String scheme, ClaimsPrincipal principal, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by martincostello** [comment]
This seems like an issue with your IdentityServer4 configuration, rather than the Nextcloud provider.

I assume you're not actually configuring the three `*Endpoint` properties to empty, otherwise the provider won't work.

**Comment by cyjbox** [comment]
yes, I configed the three endpoint like the test example:next is the code file:
https://oa.zxauto.net:7443/nextcloud/s/Z8H9kqCNSPBW2qB
