### ISSUE TITLE
I try to use github and google providers to login will have the same error, how should I fix it. 

### ISSUE THREAD

**Issue by 160905** [aspnet-contrib/AspNet.Security.OAuth.Providers#761]
### Describe the bug

``` shell
[22:42:31 Warning] Microsoft.AspNetCore.Identity.UserManager
User 7551169e-3e05-4db9-b1e9-3ab05f3afede validation failed: InvalidEmail.

[22:42:31 Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
An unhandled exception has occurred while executing the request.
System.Exception: Email '' is invalid.
   at IdentityServerHost.Quickstart.UI.ExternalController.AutoProvisionUserAsync(String provider, String providerUserId, IEnumerable`1 claims) in D:\
www\CHERRIES\src\IdentityServer\Quickstart\Account\ExternalController.cs:line 225
   at IdentityServerHost.Quickstart.UI.ExternalController.Callback() in D:\www\CHERRIES\src\IdentityServer\Quickstart\Account\ExternalController.cs:l
ine 104
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodEx
ecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, Value
Task`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, T
ask lastTask, State next, Scope scope, Object state, Boolean isCompleted)

```
I try to use github and google providers to login will have the same error, how should I fix it. 

And this is my part of code 

```
services.AddAuthentication()
      .AddGoogle(options =>
      {
          options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;

          // register your IdentityServer with Google at https://console.developers.google.com
          // enable the Google+ API
          // set the redirect URI to https://localhost:5001/signin-google
          options.ClientId = Configuration["Authentication:Google:ClientId"];
          options.ClientSecret = Configuration["Authentication:Google:ClientSecret"];
      })
      .AddGitHub(options =>
      {
          options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
          options.ClientId = Configuration["Authentication:GitHub:ClientId"];
          options.ClientSecret = Configuration["Authentication:GitHub:ClientSecret"];
          // Add email
          options.Scope.Add("user");
          options.Scope.Add("email");
          // options.Scope.Remove("email");
        
          options.ClaimActions.MapJsonKey(Claims.AvatarUrl, "avatar_url");
          options.ClaimActions.MapJsonKey(Claims.BIO, "bio");
          options.ClaimActions.MapJsonKey(Claims.BlogAddress, "blog");
      })
public static class Claims
    {
        public const string BIO = "urn:github:bio";
        public const string AvatarUrl = "urn:github:avatar_url";
        public const string BlogAddress = "urn:github:blog";
    }
```
### System information
```shell
[22:42:31 Warning] Microsoft.AspNetCore.Identity.UserManager
User 7551169e-3e05-4db9-b1e9-3ab05f3afede validation failed: InvalidEmail.

[22:42:31 Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
An unhandled exception has occurred while executing the request.
System.Exception: Email '' is invalid.
   at IdentityServerHost.Quickstart.UI.ExternalController.AutoProvisionUserAsync(String provider, String providerUserId, IEnumerable`1 claims) in D:\
www\CHERRIES\src\IdentityServer\Quickstart\Account\ExternalController.cs:line 225
   at IdentityServerHost.Quickstart.UI.ExternalController.Callback() in D:\www\CHERRIES\src\IdentityServer\Quickstart\Account\ExternalController.cs:l
ine 104
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodEx
ecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, Stat
e next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope
scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope
 scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by kevinchalet** [comment]
I fail to see how your question is related to this project?

The exception you're seeing is thrown by IdentityServer, presumably because it can't extract an email from the claims and crashes instead of ignoring that. FWIW, not all providers share the email address with client applications, and in some cases, you have to request a special scope like `email`.

Closing.
